### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by nemanjan00**
Updating dependencies for licences and security.

### CODE REVIEW

**Comment by julien-c** [comment]
Thanks!

**Comment by nemanjan00** [comment]
I will be rewriting zip part since adm-zip never resolved license problems. 

Would you like to pick zip lib? 

Would that be something you would accept as PR?

**Comment by julien-c** [comment]
Yes definitely will accept this PR. You can pick the zip lib. Thanks a ton!

**Comment by nemanjan00** [comment]
I am going to have to change the API if I want to implement it with new Zip library... Since all of them are async...

**Pull request merged**
